create database SUMERCA;
use SUMERCA;

CREATE TABLE TIPO_PRODUCTO(
ID_TIPO_PRODUCTO_PRODUCTO INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
DESCRIPCION varchar(100) not null
) ;

CREATE TABLE VENDEDOR(
ID_VENDEDOR INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
NOMBRE varchar(100) not null,
APELLIDO varchar(100) not null,
CEDULA varchar(100) not null,
ID_SUCURSAL int(11) not null
) ;

CREATE TABLE SUCURSAL(
ID_SUCURSAL_SUC INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
NOMBRE varchar(100) not null,
DIRECCION varchar(100) not null,
CIUDAD varchar(100) not null
) ;

CREATE TABLE PRODUCTO(
ID_PRODUCTO INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
ID_TIPO_PRODUCTO int(11) not null,
DESCRIPCION varchar(100) not null,
VALOR_VENTA  int(11) not null,
VALOR_COMPRA  int(11) not null
) ;

CREATE TABLE FACTURA(
NUMERO_FACTURA INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
ID_PRODUCTO_FAC int(11) not null,
ID_VENDEDOR_FAC int(11) not null,
ID_CLIENTE_FAC int(11) not null,
CANTIDAD int(11) not null,
VALOR_VENTA  int(11) not null,
FECHA_VENTA date not null
) ;

CREATE TABLE INVENTARIO(
ID_PRODUCTO_INV int(11) not null,
CANTIDAD int(11) not null
) ;

CREATE TABLE CLIENTE(
ID_CLIENTE INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
NOMBRE varchar(100) not null,
APELLIDO varchar(100) not null,
CEDULA int(20) not null,
TELEFONO int(20) not null,
DIRECCION varchar(100) not null
) ;


ALTER TABLE PRODUCTO ADD FOREIGN KEY (ID_TIPO_PRODUCTO) REFERENCES TIPO_PRODUCTO (ID_TIPO_PRODUCTO_PRODUCTO);
ALTER TABLE INVENTARIO ADD FOREIGN KEY (ID_PRODUCTO_INV) REFERENCES PRODUCTO (ID_PRODUCTO);
ALTER TABLE FACTURA ADD FOREIGN KEY (ID_PRODUCTO_FAC) REFERENCES PRODUCTO (ID_PRODUCTO);
ALTER TABLE FACTURA ADD FOREIGN KEY (ID_CLIENTE_FAC) REFERENCES CLIENTE (ID_CLIENTE);
ALTER TABLE FACTURA ADD FOREIGN KEY (ID_VENDEDOR_FAC) REFERENCES VENDEDOR (ID_VENDEDOR);
ALTER TABLE VENDEDOR ADD FOREIGN KEY (ID_SUCURSAL) REFERENCES SUCURSAL (ID_SUCURSAL_SUC);